### ISSUE TITLE
Where is abantecart files located in yunohost ? 

### ISSUE THREAD

**Issue by Citify** [YunoHost-Apps/abantecart_ynh#25]
Hello, 
This is not really an issue, more of a question. I cannot find any answers anywhere else.  

I am using Yunohost on RP4 and searching for the abandtecart files so as to be able to connect it via Filezilla. I have looked everywhere for the abantecart files in filezilla, they are not in Yunohost app file nor anywhere else. I would like to access the files so I can upload and modify files. 

Thank you.

**Comment by ghost** [comment]
Hi, sorry for the late reply. I'm not quite sure what you mean by "abantecart cart" files, if you're looking for the install directory/PHP files, normally it's in `var/www/abantecart/www`
