### ISSUE TITLE
can't log in after install

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/abantecart_ynh#26]
### Describe the bug

I can't log in after install.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.3 
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master

### Steps to reproduce

- Install the app
- Try to log in with the user and password you choose during the install

### Expected behavior

Successful login.

**Comment by thelaserguy** [comment]
I'm sorry, but how was this issue resolved?
